const API_BASE='https://app-license-api.nudroids.workers.dev';
const FALLBACK_PLANS=[
{plan_key:'1_month',name:'1 Bulan',price_cents:700,compare_at_price_cents:1000,currency:'MYR',is_featured:false},
{plan_key:'3_month',name:'3 Bulan',price_cents:1900,compare_at_price_cents:3000,currency:'MYR',is_featured:false},
{plan_key:'6_month',name:'6 Bulan',price_cents:3500,compare_at_price_cents:6000,currency:'MYR',is_featured:false},
{plan_key:'1_year',name:'1 Tahun',price_cents:5900,compare_at_price_cents:12000,currency:'MYR',is_featured:true}];
const labels={'1_month':'1 Bulan','3_month':'3 Bulan','6_month':'6 Bulan','1_year':'1 Tahun'};
const state={plans:FALLBACK_PLANS,selectedPlan:null,checkoutToken:new URLSearchParams(location.search).get('checkout')||'',checkout:null,pollTimer:null};
const plansEl=document.querySelector('#plans'),statusEl=document.querySelector('#catalog-status'),renewPlanEl=document.querySelector('#renew-plan'),dialog=document.querySelector('#checkout-dialog'),dialogTitle=document.querySelector('#dialog-title'),dialogCopy=document.querySelector('#dialog-copy'),dialogSummary=document.querySelector('#dialog-summary'),checkoutResult=document.querySelector('#checkout-result'),checkoutForm=document.querySelector('#checkout-form'),checkoutEmail=document.querySelector('#checkout-email'),checkoutCreate=document.querySelector('#checkout-create'),gatewayNote=document.querySelector('#gateway-note');
function money(c){return `RM${(Number(c||0)/100).toFixed(0)}`}; function saving(p){return Math.max(0,Number(p.compare_at_price_cents||0)-Number(p.price_cents||0))}; function labelFor(p){return labels[p.plan_key]||p.name||p.plan_key}
async function api(path,options={}){const r=await fetch(`${API_BASE}${path}`,{headers:{Accept:'application/json',...(options.headers||{})},...options});const b=await r.json().catch(()=>({ok:false,error:'invalid_response'}));if(!r.ok||!b.ok){const e=new Error(b.error||`http_${r.status}`);e.code=b.error||`http_${r.status}`;throw e}return b}
function renderPlans(plans){plansEl.innerHTML='';renewPlanEl.innerHTML='';plans.forEach(plan=>{const label=labelFor(plan),card=document.createElement('article');card.className=`plan${plan.is_featured?' featured':''}`;card.innerHTML=`${plan.is_featured?'<div class="badge">PALING BERBALOI</div>':''}<div class="plan-name">${label}</div><div class="price-old">${money(plan.compare_at_price_cents)}</div><div class="price">${money(plan.price_cents)}</div><div class="saving">Harga pelancaran · Jimat ${money(saving(plan))}</div><ul><li>Sehingga 3 peranti</li><li>Homika Cloud Sync</li><li>Encrypted Cloud Backup</li><li>Semua fungsi Homika Pro</li></ul><button class="button ${plan.is_featured?'primary':'secondary'}" type="button">Pilih ${label}</button>`;card.querySelector('button').addEventListener('click',()=>choosePlan(plan));plansEl.appendChild(card);const o=document.createElement('option');o.value=plan.plan_key;o.textContent=`${label} · ${money(plan.price_cents)}`;renewPlanEl.appendChild(o)})}
function choosePlan(plan){state.selectedPlan=plan;dialogTitle.textContent=state.checkoutToken?'Upgrade / Renew Homika Pro':'Beli Homika Pro';dialogCopy.textContent=state.checkoutToken?'Lesen semasa akan dikekalkan. Masukkan email untuk rekod pembelian.':'Masukkan email untuk menyediakan checkout Homika Pro.';dialogSummary.classList.add('hidden');checkoutResult.classList.add('hidden');checkoutForm.classList.remove('hidden');gatewayNote.classList.remove('hidden');dialog.showModal();checkoutEmail.focus()}
function renderCheckout(c){state.checkout=c;state.checkoutToken=c.token||state.checkoutToken;const plan=state.plans.find(p=>p.plan_key===c.plan_key),planText=plan?labelFor(plan):'Pilih pelan',amount=c.amount_cents==null?'Belum dipilih':money(c.amount_cents),lic=c.license_hint?` · ${c.license_hint}`:'';dialogSummary.innerHTML=`<div><strong>${c.reference}</strong></div><div>${c.action==='renew'?'Renewal':'Pembelian'} · ${planText} · ${amount}${lic}</div><div>Status: <strong>${c.status}</strong></div>`;dialogSummary.classList.remove('hidden');checkoutResult.classList.remove('hidden');if(c.status==='completed'){checkoutForm.classList.add('hidden');gatewayNote.classList.add('hidden');checkoutResult.innerHTML=c.action==='buy'&&c.license_key?`<strong>Pembayaran disahkan.</strong><p>Kod lesen Homika Pro anda:</p><code>${c.license_key}</code><p>Simpan kod ini dan aktifkan dalam aplikasi.</p>`:`<strong>Renewal berjaya.</strong><p>Kod lesen yang sama telah dipanjangkan. Kembali ke Homika dan tekan <b>Semak sekarang</b>.</p>`;stopPolling()}else checkoutResult.innerHTML=`<strong>Checkout sudah disediakan.</strong><p>Rujukan ${c.reference} menunggu payment gateway. Tiada bayaran dicaj dari halaman ini sekarang.</p>`}
async function createSelectedCheckout(email){const plan=state.selectedPlan;if(!plan)return;if(state.checkoutToken){const b=await api('/v1/store/checkout/select-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({checkout_token:state.checkoutToken,plan_key:plan.plan_key,email})});renderCheckout(b.checkout);startPolling()}else{const b=await api('/v1/store/checkout-intents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'buy',plan_key:plan.plan_key,email})});renderCheckout(b.checkout);startPolling()}}
async function loadCatalog(){try{const b=await api('/v1/store/catalog');if(!Array.isArray(b.plans)||!b.plans.length)throw new Error();state.plans=b.plans;statusEl.textContent='Harga terkini dari Homika licence server.'}catch(_){state.plans=FALLBACK_PLANS;statusEl.textContent='Menggunakan harga pelancaran yang disimpan pada halaman ini.'}renderPlans(state.plans)}
async function loadCheckoutToken(){if(!state.checkoutToken)return;try{const b=await api(`/v1/store/checkout?token=${encodeURIComponent(state.checkoutToken)}`);state.checkout=b.checkout;if(b.checkout.status==='completed'){dialogTitle.textContent='Homika Pro';dialogCopy.textContent='Status checkout anda.';checkoutForm.classList.add('hidden');dialog.showModal();renderCheckout(b.checkout)}else{statusEl.textContent=b.checkout.license_hint?`Renewal dipaut kepada lesen ${b.checkout.license_hint}. Pilih pelan di bawah.`:'Sesi renewal aktif. Pilih pelan di bawah.';document.querySelector('#pricing').scrollIntoView()}}catch(_){state.checkoutToken=''}}
function startPolling(){stopPolling();if(!state.checkoutToken)return;state.pollTimer=setInterval(async()=>{try{renderCheckout((await api(`/v1/store/checkout?token=${encodeURIComponent(state.checkoutToken)}`)).checkout)}catch(_){ }},8000)} function stopPolling(){if(state.pollTimer)clearInterval(state.pollTimer);state.pollTimer=null}
checkoutForm.addEventListener('submit',async e=>{e.preventDefault();const email=checkoutEmail.value.trim().toLowerCase();if(!email)return;checkoutCreate.disabled=true;checkoutCreate.textContent='Menyediakan…';try{await createSelectedCheckout(email);checkoutForm.classList.add('hidden')}catch(err){checkoutResult.classList.remove('hidden');checkoutResult.textContent=`Checkout tidak dapat disediakan (${err.code||'error'}).`}finally{checkoutCreate.disabled=false;checkoutCreate.textContent='Sediakan checkout'}})
document.querySelector('#renew-form').addEventListener('submit',async e=>{e.preventDefault();const email=document.querySelector('#renew-email').value.trim().toLowerCase(),lic=document.querySelector('#renew-license').value.trim().toUpperCase(),plan=state.plans.find(i=>i.plan_key===renewPlanEl.value);if(!email||!lic||!plan)return;try{const b=await api('/v1/store/checkout-intents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'renew',email,license_key:lic,plan_key:plan.plan_key})});state.checkoutToken=b.checkout.token;state.selectedPlan=plan;dialogTitle.textContent='Renew Homika Pro';dialogCopy.textContent='Kod lesen yang sama akan digunakan selepas bayaran disahkan.';checkoutForm.classList.add('hidden');dialog.showModal();renderCheckout(b.checkout);startPolling()}catch(err){alert(`Renewal tidak dapat disediakan (${err.code||'error'}).`)}})
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
(async()=>{await loadCatalog();await loadCheckoutToken();const action=new URLSearchParams(location.search).get('action');if(action==='renew'&&!state.checkoutToken)document.querySelector('#renew').scrollIntoView();if(action==='buy')document.querySelector('#pricing').scrollIntoView()})();
